# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Jekyll collections settings
# 6. Site settings
# 7. Prose settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .jekyll-cache
- Vagrantfile

# 2. Installed Gems
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# 3. Gem settings
author: name
twitter:
  username: 
  card: summary #keep this to generate a twitter share card
social:
  name: name
  links:
    - https://www.instagram.com/cevrevesokakhayvanlari
    - https://www.facebook.com/cevrevesokakhayvanlaridernegi


# 4. Jekyll settings
sass:
  sass_dir: assets/css
timezone: Europe/Istanbul

# 5. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: pet # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 6. Site settings
encoding: utf-8
lang: tr
url: "https://pet.olcay.dev" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Çevre ve Sokak Hayvanları Derneği" # the name of your site, e.g. ACME Corp.
tagline: "kedi,köpek,barınak,dernek,hayvan,hayvan sahiplen"
email: your.email@gmail.com
description: >-
 Gönüllülerin bağışları ile sokak canları için çalışıyoruz. Her türlü yardımlarınız ve can sahiplenme için bize ulaşabilirsiniz.
repo: "https://github.com/otomatikmuhendis/petibor"


# 7. Prose.io settings
prose:
  rooturl: '_posts'
  media: 'images'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Başlık"
          placeholder: "İlan Başlığı"
          alterable: true
      - name: "name"
        field:
          element: "text"
          label: "İsmi"
          placeholder: "İsmi"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Resim"
          help: "Anasayfada görüntülenmesini istediğiniz resim."
          placeholder: "/images/..."
          alterable: true
      - name: "gender"
        field:
          element: "select"
          label: "Cinsiyeti"
          alterable: true
          options:
            - name: 'Dişi'
              value: 'Dişi'
            - name: 'Erkek'
              value: 'Erkek'
      - name: "age"
        field:
          element: "select"
          label: "Yaşı"
          alterable: true
          options:
            - name: 'Yavru (0 - 6 Aylık)'
              value: 'Yavru (0 - 6 Aylık)'
            - name: 'Genç (6 Aylık - 2 Yaş)'
              value: 'Genç (6 Aylık - 2 Yaş)'
            - name: 'Yetişkin (2 - 7 Yaş)'
              value: 'Yetişkin (2 - 7 Yaş)'
            - name: 'Yaşlı (7 Yaş ve üzeri)'
              value: 'Yaşlı (7 Yaş ve üzeri)'
      - name: "race"
        field:
          element: "select"
          label: "Irkı"
          alterable: true
          options:
            - name: 'Tekir'
              value: Tekir'
            - name: 'Siyam'
              value: 'Siyam'
            - name: 'Scottish'
              value: 'Scottish'
            - name: 'Diğer'
              value: 'Diğer'
      - name: "tags"
        field:
          element: "multiselect"
          label: "Etiketler"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Yayınla"
          help: "Yayınlamak için onaylayın"